'use client';
import {create} from 'zustand';
import {persist,createJSONStorage} from 'zustand/middleware';
import type {Developer,Repository} from '@/lib/github/types';
export interface Note {id:string;title:string;content:string;tag:string;pinned:boolean;createdAt:number;updatedAt:number}
export type SavedDeveloper=Pick<Developer,'login'|'name'|'avatar_url'|'bio'|'html_url'>;
export type SavedRepository=Pick<Repository,'id'|'name'|'full_name'|'description'|'language'|'stargazers_count'|'html_url'>;
export interface Recent {kind:'developer'|'repository';label:string;url:string}
export interface Preferences {theme:'dark'|'light'|'system';collapsed:boolean;reducedMotion:boolean;hour24:boolean;defaultUsername:string;repoView:'grid'|'list';widgets:{clock:boolean;focus:boolean;notes:boolean;recent:boolean}}
export const defaults:Preferences={theme:'dark',collapsed:false,reducedMotion:false,hour24:true,defaultUsername:'',repoView:'grid',widgets:{clock:true,focus:true,notes:true,recent:true}};
interface Workspace {preferences:Preferences;selectedUsername:string;developers:SavedDeveloper[];repositories:SavedRepository[];notes:Note[];recent:Recent[];setPreferences:(p:Partial<Preferences>)=>void;select:(name:string)=>void;toggleDeveloper:(d:Developer)=>void;toggleRepository:(r:Repository)=>void;removeSaved:(kind:'developers'|'repositories',id:string|number)=>void;clearSaved:(kind:'developers'|'repositories')=>void;addRecent:(r:Recent)=>void;removeRecent:(url?:string)=>void;saveNote:(n:Note)=>void;deleteNote:(id:string)=>void;reset:()=>void}
const initial={preferences:defaults,selectedUsername:'',developers:[],repositories:[],notes:[],recent:[]};
export const useWorkspace=create<Workspace>()(persist((set)=>({...initial,setPreferences:p=>set(s=>({preferences:{...s.preferences,...p}})),select:selectedUsername=>set({selectedUsername}),toggleDeveloper:d=>set(s=>({developers:s.developers.some(x=>x.login===d.login)?s.developers.filter(x=>x.login!==d.login):[...s.developers,{login:d.login,name:d.name,avatar_url:d.avatar_url,bio:d.bio,html_url:d.html_url}]})),toggleRepository:r=>set(s=>({repositories:s.repositories.some(x=>x.id===r.id)?s.repositories.filter(x=>x.id!==r.id):[...s.repositories,{id:r.id,name:r.name,full_name:r.full_name,description:r.description,language:r.language,stargazers_count:r.stargazers_count,html_url:r.html_url}]})),removeSaved:(kind,id)=>set(s=>kind==='developers'?{developers:s.developers.filter(d=>d.login!==id)}:{repositories:s.repositories.filter(r=>r.id!==id)}),clearSaved:kind=>set({[kind]:[]}),addRecent:r=>set(s=>({recent:[r,...s.recent.filter(x=>x.url!==r.url)].slice(0,16)})),removeRecent:url=>set(s=>({recent:url?s.recent.filter(r=>r.url!==url):[]})),saveNote:n=>set(s=>({notes:s.notes.some(x=>x.id===n.id)?s.notes.map(x=>x.id===n.id?n:x):[n,...s.notes]})),deleteNote:id=>set(s=>({notes:s.notes.filter(n=>n.id!==id)})),reset:()=>set(initial)}),{name:'devpulse-workspace-v1',storage:createJSONStorage(()=>localStorage),partialize:s=>({preferences:s.preferences,developers:s.developers,repositories:s.repositories,notes:s.notes,recent:s.recent}),skipHydration:true}));
